//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int product_id { get; set; }
        public double price1 { get; set; }
        public System.DateTime apply_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public int price_id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
