//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int staff_id { get; set; }
        public string staff_name { get; set; }
        public string phone { get; set; }
        public string identify { get; set; }
        public byte role { get; set; }
        public string account { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
