//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_order
    {
        public int order_id { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> staff_id { get; set; }
        public System.DateTime pay_day { get; set; }
        public Nullable<short> used_mark { get; set; }
        public Nullable<double> paid_price { get; set; }
    }
}
