//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_product_detail
    {
        public Nullable<int> category_id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public int product_id { get; set; }
        public string product_name { get; set; }
        public short quantity { get; set; }
        public string category_name { get; set; }
        public string brand_name { get; set; }
    }
}
